### ISSUE TITLE
Cloudflare Pages build fails with `EISDIR: illegal operation on a directory, read`

### ISSUE THREAD

**Issue by groenroos** [11ty/eleventy-plugin-vite#56]
I'm trying to convert a project to use this plugin, and while the production build works on `localhost`, but when trying to build with Cloudflare Pages, it fails every time with seemingly two errors; `EISDIR: illegal operation on a directory, read` and `ENOENT: no such file or directory, lstat '/opt/buildhome/repo/.11ty-vite'`.

The first error seemingly suggests that the built page from Eleventy (`/opt/buildhome/repo/.11ty-vite/pages/this-is-a-test-page/index.html`) is a directory, and not a file. The second error claims that the `.11ty-vite` directory does not exist at all.

- Eleventy 3.0.0
- Eleventy Vite Plugin 5.0.0
- Vite 5.4.10
- Node 22.9.0 / npm 9.6.7
- Environment Cloudflare Pages v2 (Ubuntu 22.04.2 / x86_64 / gVisor)

Related to #15, #36. While similar to vitejs/vite#4030, that bug was apparently fixed 2 years ago; and identified to be triggered by empty `src=""` or `href=""` attributes, which at least my successful build on localhost does not contain.

I have not been able to reproduce this error on my local environment (same as above, except macOS Sonoma 14.4.1), or on the GitHub Actions runner (same env, but on `ubuntu-latest`); but it happens every single time on the Cloudflare Pages build.

<details><summary>Eleventy / Vite config</summary>

```js
import EleventyVitePlugin  from "@11ty/eleventy-plugin-vite";
import viteSassGlobImports from 'vite-plugin-sass-glob-import';
import viteGlsl            from 'vite-plugin-glsl';
import viteVue             from '@vitejs/plugin-vue2';
import viteLegacy          from '@vitejs/plugin-legacy';
import autoprefixer        from 'autoprefixer';

export default function(eleventyConfig) {
	eleventyConfig.addPlugin(EleventyVitePlugin, {
		viteOptions: {
			tempFolderName: '.11ty-vite',

			publicDir: 'site/public',
			clearScreen: false,
			logLevel: 'warn',

			assetsInclude: ['**/*.xml', '**/*.txt', '**/*.json'],

			server: {
				mode: 'development',
				middlewareMode: true,
			},

			build: {
				mode: 'production',
				sourcemap: 'true',
				manifest: true,
			},

			plugins: [
				viteSassGlobImports(),
				viteVue(),
				viteLegacy(),
				viteGlsl(),
			],

			css: {
				postcss: {
					plugins: [
						autoprefixer(),
					],
				},
				preprocessorOptions: {
					scss: {
						quietDeps: true,
					},
				},
			},

			resolve: {
				alias: {
					createjs: '@thegraid/createjs-module',
					'~': path.resolve('.', 'node_modules'),
				}
			}
		}
	});

	/* .. */
}
```

</details>

<details><summary>Log output</summary>

```
2024-11-08T22:00:38.985234Z	[36mvite v5.4.10 [32mbuilding for production...[36m[39m
2024-11-08T22:00:39.696653Z	transforming...
2024-11-08T22:00:45.568959Z	[32m✓[39m 765 modules transformed.
2024-11-08T22:00:45.575895Z	[31mx[39m Build failed in 6.57s
2024-11-08T22:00:45.576736Z	[11ty] Encountered a Vite build error, restoring original Eleventy output to ./build/ [31m[vite:build-html] EISDIR: illegal operation on a directory, read[39m
2024-11-08T22:00:45.592071Z	file: [36m/opt/buildhome/repo/.11ty-vite/pages/this-is-a-test-page/index.html[39m
2024-11-08T22:00:45.592254Z	    at async readFileHandle (node:internal/fs/promises:554:24)
2024-11-08T22:00:45.592398Z	    at async fileToBuiltUrl (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:20427:19)
2024-11-08T22:00:45.592526Z	    at async processAssetUrl (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:35240:22)
2024-11-08T22:00:45.592686Z	    at async file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:35356:48
2024-11-08T22:00:45.592849Z	    at async Promise.all (index 0)
2024-11-08T22:00:45.593107Z	    at async Object.transform (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:35420:9)
2024-11-08T22:00:45.593274Z	    at async transform (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:19640:16)
2024-11-08T22:00:45.593389Z	    at async ModuleLoader.addModuleSource (file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:19856:36) {
2024-11-08T22:00:45.593505Z	  errno: -21,
2024-11-08T22:00:45.593602Z	  code: 'PLUGIN_ERROR',
2024-11-08T22:00:45.593709Z	  syscall: 'read',
2024-11-08T22:00:45.593825Z	  pluginCode: 'EISDIR',
2024-11-08T22:00:45.59397Z	  plugin: 'vite:build-html',
2024-11-08T22:00:45.59408Z	  hook: 'transform',
2024-11-08T22:00:45.594244Z	  id: '/opt/buildhome/repo/.11ty-vite/pages/this-is-a-test-page/index.html',
2024-11-08T22:00:45.594362Z	  watchFiles: [
2024-11-08T22:00:45.594478Z	    '/opt/buildhome/repo/.11ty-vite/blog/blog-post-1/index.html',
2024-11-08T22:00:45.594606Z	    '/opt/buildhome/repo/.11ty-vite/blog/blog-post-2/index.html',
2024-11-08T22:00:45.600154Z	    'apple-touch-icon.png',
2024-11-08T22:00:45.600411Z	    'favicon-32x32.png',
2024-11-08T22:00:45.600489Z	    'favicon-16x16.png',
2024-11-08T22:00:45.600557Z	    'site.webmanifest',
2024-11-08T22:00:45.60082Z	    'favicon.ico',
2024-11-08T22:00:45.601332Z	    'images/blog/blog-post-1/image.png',
2024-11-08T22:00:45.601456Z	    'images/blog/blog-post-2/picture.png',
2024-11-08T22:00:45.610352Z	    ... 2073 more items
2024-11-08T22:00:45.61044Z	  ]
2024-11-08T22:00:45.610522Z	}
2024-11-08T22:00:45.750501Z	[11ty] Problem writing Eleventy templates:
2024-11-08T22:00:45.751035Z	2024-11-08T22:00:45.750Z Eleventy:EleventyErrorHandler Full error object: "[Error: ENOENT: no such file or directory, lstat '/opt/buildhome/repo/.11ty-vite'] {\n" + '  errno: -2,\n' + "  code: 'ENOENT',\n" + "  syscall: 'lstat',\n" + "  path: '/opt/buildhome/repo/.11ty-vite'\n" + '}'
2024-11-08T22:00:45.751277Z	[11ty] ENOENT: no such file or directory, lstat '/opt/buildhome/repo/.11ty-vite'
2024-11-08T22:00:45.751437Z	2024-11-08T22:00:45.750Z Eleventy:EleventyErrorHandler (error stack): Error: ENOENT: no such file or directory, lstat '/opt/buildhome/repo/.11ty-vite'
```

</details>

**Comment by KiwiKilian** [comment]
Thanks for your report. First of all, I've no experience around Cloudflare Pages/Worker.

If I understand correctly, the build is happening within their worker environment "Wrangler", which only has limited [Node.js compatibility](https://developers.cloudflare.com/workers/runtime-apis/nodejs/#nodejs-api-polyfills), right? Looking at the [compatibility matrix](https://workers-nodejs-compat-matrix.pages.dev/), there is nearly no support for any of the `node:fs` functionality, which is used to rename directories during the build with this plugin.

I see two possibilities:

- Trying to get rid of the usage for `node:fs` within this plugin
  - This could be some kind of build only mode, which spares the directory renaming/copy, would have to investigate
- Build within another environment (like GitHub Actions) and only push the build result to Cloudflare Pages (is that possible?)

**Comment by KiwiKilian** [comment]
Ok, the Build env is definitely separate from Workers an should support `node:fs` as far as I can tell. Does the build env definitely also use Node 22? Could you try deploying a minimal reproduction to Cloudflare Pages (like the setup in `example` of this repository)?

**Comment by KiwiKilian** [comment]
I've created this very simple [repository](https://github.com/KiwiKilian/eleventy-plugin-vite-cloudflare-pages), which deployed successful: https://eleventy-plugin-vite-cloudflare-pages.pages.dev/. I reproduction would be necessary.

**Comment by KiwiKilian** [comment]
I think the template of `/pages/this-is-a-test-page/index.html` and the HTML which is generated by Eleventy, but not successfully processed by Vite, would be interesting to further investigate.

I can create such error locally by using such template:
```html
<!doctype html>
<html lang="en">
<head>
    <link href="/" />
</head>
</html>
```

Maybe some config is different on Cloudflare Pages and therefore the build output is different?

**Comment by groenroos** [comment]
Thanks for the in-depth response! 💪 

The environment on Pages is the same as GHA and `localhost` far as I can tell (apart from the OS), including all `.env` variables. I noticed that the build was configured to be triggered via `make` on CFP, although it in turn just calls `npm run prod` as we do on GHA and `localhost`. Configuring CFP to run `npm run prod` directly without `make` did not make a difference.

The build always complains about the same file, which happens to be one [generated from data via pagination](https://www.11ty.dev/docs/pages-from-data/). The file is the newest/first entry of the data source. Removing this entry from the data source doesn't fix it; the same error simply happens for the then-newest entry.

Interestingly though, deleting the entire data file that fetches the data these pages are generated from seems to fix the build on Cloudflare 🤔 

Despite the pages being generated from data, they aren't significantly or obviously different to our manually defined pages - they use the same layout, and all the same techniques as other pages. Worth also noting that there are other pages in our project that are generated from other data files with remote sources, and these build fine on Cloudflare. There's nothing obvious I can think of that's different about these problem pages or the data they're based on, compared to the working ones.

Since it always builds on local, I searched the built source of the page the error complains about. There are zero instances of `src=""`, `src="/"`, or `href=""` anywhere on this page; and the only two instances of `href="/"` are attached to `<a>` tags, not to `<link>` or such.

There are a number of `<img src="data:image/svg+xml...` tags with urlencoded SVG markup; but this is generated by Vite or Eleventy, and does not exist on our source. These are also in the site nav, and so supposably aren't a problem on the working build where the problem pages have been deleted.

Other `src` attributes point to either the `/assets` folder built by Vite, or to fully-qualified URLs with `https`. Nothing out of the ordinary for `href` attributes either; and in both cases, 95% of these are in the global site layout which builds fine when the data file is deleted.

According to `test`, the generated `/pages/this-is-a-test-page/index.html` file in the `build` folder on `localhost` is definitely a file, and not a directory; and chmod looks reasonable at `644`. No easy way to check that these are the same during the build on the CFP environment, though.

Since the data is used in various places of the site, I'll try to narrow down the problem a bit further by re-enabling the files I deleted one-by-one to see at what point the build breaks.

Let me know if you have any other ideas on where to look!

**Comment by KiwiKilian** [comment]
I guess you can't download the build output, if the script fails?

But you could disable the Vite plugin. Then you can download the output of Eleventy from CFP, before it would be processed by Vite and investigate further.

**Comment by groenroos** [comment]
> I guess you can't download the build output, if the build fails?

Correct; the environment is deleted and never deployed is the build results in an error. I suppose I can edit the `npm` script to include additional commands, though?

> But you could disable the Vite plugin. Then you can download the output of Eleventy from CFP, before it would be processed by Vite and investigate further.

Removing the Vite plugin does make the build succeed.

There isn't a way to download an entire deployment from CFP; I grabbed the HTML served by the Vite-less deployment, but it's the same story; no `src=""`, `src="/"`, or `href=""` anywhere, and only two instances of `href="/"` in `<a>` tags, both in the global layout.

Inspecting the unique content of the page line-by-line, and I can't see anything suspect either.

Is it possible that the `EISDIR` error isn't related to anything _on_ this particular page, but perhaps to some other place that's trying to open/use this page; maybe before it's been generated? Maybe it's caught in passthrough copy somehow or something?

**Comment by KiwiKilian** [comment]
Wonderful! Helped me to improve the error handling quite a bit, which should help others to identify if it's a plugin or Vite problem.
